# Generated by Django 4.1.7 on 2023-03-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username_color",
            field=models.CharField(default="white", max_length=50, verbose_name="Цвет"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="users/avatar/nomedal.svg",
                upload_to="users/",
                verbose_name="Аватар",
            ),
        ),
    ]
