# Generated by Django 4.1.7 on 2023-03-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_username_color_alter_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="scores",
        ),
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Баланс"),
        ),
    ]
